### ISSUE TITLE
Implements i18n

### ISSUE THREAD

**Issue by allustin** [racodond/sonar-gherkin-plugin#41]
Gherkin contains many lang ;-)

in this file

https://github.com/racodond/sonar-gherkin-plugin/blob/master/gherkin-frontend/src/main/java/org/sonar/gherkin/parser/GherkinLexicalGrammar.java

it will be useful to use this JSON as a keywords definition from this 

https://github.com/cucumber/gherkin-java/blob/master/src/main/resources/gherkin/gherkin-languages.json

**Comment by racodond** [comment]
> Gherkin contains many lang ;-)

I know :-)

> in this file
> 
> https://github.com/racodond/sonar-gherkin-plugin/blob/master/gherkin-frontend/src/main/java/org/sonar/gherkin/parser/GherkinLexicalGrammar.java
> 
> it will be useful to use this JSON as a keywords definition from this
> 
> https://github.com/cucumber/gherkin-java/blob/master/src/main/resources/gherkin/gherkin-languages.json

Thanks for the pointer!

I first wanted to craft a version that supports well my needs. That's why it is limited to English for now. I'm almost done with it (will be done when version 1.2 is released, likely next week). Then, I'll tackle internationalization:

- Grammar (this ticket)
- Spell checker (https://github.com/racodond/sonar-gherkin-plugin/issues/42)
- Update of rule "Source code should be properly indented" that is tight to English keywords for now.

**Comment by allustin** [comment]
@racodond if you write a simple COTRIBIUTORS.md - iam and @nixel2007 can create pull request for you with our version of implementation this ticket.

**Comment by nixel2007** [comment]
@allustin please note, that we can't use native Gherkin java library, as we did it in our version of plugin. This one needs to improve lexer itself.

**Comment by racodond** [comment]
Great news if you feel like contributing!
Before I find some time to create a CONTRIBUTORS.md file, just create a pull request and I'll review it.

**Comment by racodond** [comment]
@allustin @nixel2007 Here's a snapshot supporting i18n: https://github.com/racodond/sonar-gherkin-plugin/releases/tag/i18n
It would be great if you could give it a try and provide some feedback.
Thanks!

**Comment by nixel2007** [comment]
@racodond good to hear you've done it fast!
I think, we can try new version tommorow (we are UTC+3), we have plenty of ru-features

**Comment by racodond** [comment]
Cool! Looking forward to getting your feedback!

**Comment by nixel2007** [comment]
@racodond it works like a charm!
![image](https://cloud.githubusercontent.com/assets/1132840/21419865/4b7d023a-c83b-11e6-84e0-e0bef50dc513.png)
A few comments - it's common to name feature files in native language. I think the gherkin:S1578 rule should be feeded with more perissable chars.

Also looks like your highlighter doen't highlight comments properly. Is this `kind` is correct https://github.com/racodond/sonar-gherkin-plugin/blob/master/gherkin-frontend/src/main/java/org/sonar/gherkin/visitors/SyntaxHighlighterVisitor.java#L94 ?

**Comment by racodond** [comment]
@nixel2007 

> it works like a charm!

Cool! Thanks for your feedback!

> Also looks like your highlighter doesn't highlight comments properly

The highlighter is working fine on comments. Actually, I don't consider language declarations as comments. That's why it is not highlighted as a comment in your screenshot.
Anyway, I just updated the plugin to add a specific highlighting for language declarations (green). See https://github.com/racodond/sonar-gherkin-plugin/commit/ed6f736d14c699bd75044147c5476204fa209848

![image](https://cloud.githubusercontent.com/assets/1215713/21423576/0af6b67c-c83e-11e6-837d-c432ae825694.png)

A new snapshot is available with this fix at https://github.com/racodond/sonar-gherkin-plugin/releases/tag/1.3-RC1


> it's common way to name feature files in native language. I think the gherkin:S1578 rule should be feeded with more permissable chars

I prefer to leave the rule as it is. It should be the user's responsibility to set the right regular expression parameter depending on their needs, language, etc.

**Comment by nixel2007** [comment]
@racodond i have a parser error in features with tags and "Функционал" keyword (feature-keyword)
```gherkin

# encoding: utf-8
# language: ru

#https://github.com/silverbulleters/vanessa-behavior/issues/237

@IgnoreOnCIMainBuild


Функционал: Тестовая фича, проверяющая генерацию снипета по структуре сценария
 


Структура сценария: Привязка файлов сканов актов к документам ЭСТИ
	Допустим к заказу связанному с реализацией товаров и услуг <Номер> от <ДатаДокумента>  присоединен файл <ИмяФайла> только один

		
	Примеры:
		| ТомХраненияПервички 	| МесяцГода   | Реализации | АктИсх  | ИмяФайла 	| Номер | ДатаДокумента | 
		| ПутьКТому 			| 2015.06     | Реализации | Акт исх | ИмяФайла.pdf | 524   | 2015.06.30    |		

```

can you check this?

**Comment by racodond** [comment]
@nixel2007 

I check that the language declaration as the first line of a file. It is on the second line in your example. Thus, the file is considered as being written in the default language (en). Hence the parse error.

Can language declaration be on the second line? How about the encoding declaration? Could you please point to some documentation defining where language, encoding, etc. declarations are supposed to be?

Thanks

David

**Comment by nixel2007** [comment]
@racodond the official spec says, that language declaration must be at first line of the file
https://github.com/cucumber/cucumber/wiki/Spoken-languages

however the Feature Introduction says that there can be `encoding` comment also - https://github.com/cucumber/cucumber/wiki/Feature-Introduction

I think you could read all comments until any non-comment with text, check the language in this comments and if you found it - feed the parser with given lang.

**Comment by racodond** [comment]
@nixel2007 I'll find out a way to support language and encoding whatever the order... after Christmas.

**Comment by nixel2007** [comment]
@racodond sure, thanks a lot! 
Merry Christmas :)

**Comment by racodond** [comment]
@nixel2007 Thanks!
I just had a look at https://github.com/cucumber/gherkin and I can't find any piece of code dealing with encoding. It looks like this is not supported even if it is written in one single (of many) documentation. Are you sure that it is really taken into account in your feature file? What if you set it to something else like "blabla"? Does it really change the behavior? Or is it just ignored and interpreted as a simple comment?

**Comment by nixel2007** [comment]
@racodond in most cases I use our own implemantation of Gherkin Language, and no, we just interpretate it as a comment. originaly parser was based on Gherkin v3, maybe cucumber team just removed it in v4.
We can change our instrument to not generate this #encoding line on new features, but we already have a lot (thousands on hundreds of clients) feature-file with this line, so i'll be much obliged if gherkin-plugin will also interprete it as comment. Maybe we can add some new rule, lets say `language must be defined on only first line` in case parser get it at any other line than first.

**Comment by racodond** [comment]
@nixel2007 I'm not really keen on adding support of encoding. I'd prefer that you change your "instrument" to not generate this encoding line. And talk with your clients to proceed with a search and replace to remove those lines.

**Comment by nixel2007** [comment]
@racodond Ok!
Thank you anyway, it works and works good!

**Comment by racodond** [comment]
@nixel2007 Thanks for your understanding and the kind words!
