### ISSUE TITLE
Feature files not picked up

### ISSUE THREAD

**Issue by Asdafers** [racodond/sonar-gherkin-plugin#52]
Hi,
the plugin is not picking up the feature files regardless of me forcefully setting both the language and the folders to include. I'm using maven 3.3.9, maven-sonar plugin 3.2, sonar 6.2 and 1.3 version of your plugin.

Any ideas what I'm doing wrong?

Thanks

**Comment by racodond** [comment]
Hi @Asdafers,

Could you please send me your project (or at least, the pom file and the source code directory with one of your feature files)? Could you also send me the log file of the analysis in debug mode?

Thank you

David

**Comment by racodond** [comment]
Hi @Asdafers,

I got other questions related to Maven analysis. I updated the README file: https://github.com/racodond/sonar-gherkin-plugin#maven. It is likely you face the same configuration issue.

Keep me posted

David

**Comment by racodond** [comment]
@Asdafers I'm closing the issue. Feel free to comment if you still face some issue to analyze your Gherkin code.
