### ISSUE TITLE
Support scenarios with two 'Examples' sections

### ISSUE THREAD

**Issue by damianszczepanik** [racodond/sonar-gherkin-plugin#53]
`CRITICAL SonarQube violation: Parse error at line 97 column 5:

 @myTag
   Examples:
     | unitName       | unitCode |
     | myUnit | myCode |
 
  Examples:
       ^
    | unitName       | unitCode |
    | myUnit1 | myCode1 |
`

Because we use tag for some examples, we need to provide two sections of Example. It works pretty nice with Cucumber - at least this is what we verified using cucumber report so I think that the problem is with the parser that does not support such case.

**Comment by racodond** [comment]
Hi @damianszczepanik,

Thanks for your feedback!

Indeed, it looks like it is possible: https://github.com/cucumber/cucumber/blob/master/gherkin/ruby/lib/gherkin/ast_builder.rb#L175
I will try to work on it for next version.

David

**Comment by racodond** [comment]
Rules to update:
* MissingDataTableColumnCheck
* UnusedVariableCheck
