### ISSUE TITLE
Change 'allowed-tags' rule parameter from a comma-separated list to a regular expression

### ISSUE THREAD

**Issue by Bertk** [racodond/sonar-gherkin-plugin#57]
@racodond We use [SpecFlow](http://specflow.org/) and want to use references in feature tags to synchronize TFS work items or test cases (https://www.youtube.com/watch?v=uhZH81sMMfs).
I implemented a plugin already with the rule "allowed-composite-tag" (see https://github.com/Bertk/sonar-gherkin-custom-rules-plugin/).
**Can this rule be added to the SonarQube Gherkin plugin?** 
_The current solution of a separate plugin with only one single rule is somehow overdone._

see #58

**Comment by racodond** [comment]
@Bertk: My apologies for the long long long delay... Version 1.6 has just been released: https://github.com/racodond/sonar-gherkin-plugin/releases/tag/1.6

**Comment by Bertk** [comment]
@racodond Thank you :christmas_tree:
