### ISSUE TITLE
Metrics in SonarQube 6.6

### ISSUE THREAD

**Issue by lenntt** [racodond/sonar-gherkin-plugin#59]
Thanks for making this plugin available.
Probably more a question based on my inexperience (and outdated docs?):

I was wondering, how to use the metrics mentioned in the Readme, I'm not seeing them in sonarqube 6.6, JS project.
Only the defaults in /admin/custom_metrics.

**Comment by racodond** [comment]
Hi @lenntt,

> Thanks for making this plugin available.

My pleasure!

> Probably more a question based on my inexperience (and outdated docs?):
> I was wondering, how to use the metrics mentioned in the Readme, I'm not seeing them in sonarqube 6.6, JS project.
> Only the defaults in /admin/custom_metrics.

I'm not sure to understand. Are you talking about the following section in the Readme file: https://github.com/racodond/sonar-gherkin-plugin#metrics ? If so, it means that:

- `Statement` as SonarQube metric corresponds to a `Step` in Gherkin
- `Function` as SonarQube metric corresponds to a `Scenario` in Gherkin
- `Class` as SonarQube metric corresponds to a `Feature` in Gherkin

For instance, if your Gherkin project in SonarQube states that there is 25 functions, it means that your Gherkin project has 25 scenarios total.

All those metrics are available through the Measures tab: https://sonarcloud.io/component_measures?id=com.racodond.sonarqube.plugin.gherkin%3Agherkin&metric=statements

**Comment by lenntt** [comment]
Aaah, got it!
Thanks for the quick&helpful answer
