### ISSUE TITLE
Plugin not working when used with SonarCloud

### ISSUE THREAD

**Issue by MirzaSB** [racodond/sonar-gherkin-plugin#67]
Hello,

So I wanted to use the plugin with SonarCloud, so I added the following in the pom.xml file of my Java project.

`        <dependency>
            <groupId>com.racodond.sonarqube.plugin.gherkin</groupId>
            <artifactId>sonar-gherkin-plugin</artifactId>
            <version>1.7</version>
        </dependency>`

`<sonar.sources>pom.xml,src/main/java,src/test/resources/features</sonar.sources>` (properties section).

I ran the command, "mvn clean install sonar:sonar". The command ran successfully, but the Gherkin plugin did not run or find any issues.

Is there anything that I'm missing?

**Comment by nixel2007** [comment]
Plugin must be installed on sonarcloud server, you can't (AFAIK) just add a dependency to get results on server.

**Comment by MirzaSB** [comment]
@nixel2007 

How can we install the plugin in the sonarcloud server?

**Comment by nixel2007** [comment]
You must be a sonarcloud admin :)

You can install your own sonarqube instance with plugins you need

**Comment by racodond** [comment]
Hi @MirzaSB,

Only SonarSource plugins are available on Sonarcloud. Thus, unfortunately, it is not possible to analyze Gherkin code on Sonarcloud.

David
