### ISSUE TITLE
add sonarlint supported config prop

### ISSUE THREAD

**Issue by allustin** [racodond/sonar-gherkin-plugin#68]
https://github.com/SonarSource/sonarlint-core/blob/master/its/plugins/javascript-custom-rules/pom.xml#L60

**Comment by racodond** [comment]
Hi @allustin,

SonarSource is blocking all non-SonarSource plugins to run in SonarLint, so it's not possible to make it work even with this flag.

David

**Comment by nixel2007** [comment]
But you can fork and recompile sonarlint-core to whitelist your plugins :)
