### ISSUE TITLE
false-positive when pystring contains '<...>'

### ISSUE THREAD

**Issue by Bertk** [racodond/sonar-gherkin-plugin#69]
The rule **missing-data-table-column**  should ignore "pystrings (Doc Strings)" in a scenario (see screenshot, source file https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/integration-tests/features/test_execution_statistics.feature)
<img width="555" alt="fp" src="https://user-images.githubusercontent.com/2315215/48977210-a3488680-f096-11e8-89e8-dbdc30b225fb.PNG">

**Comment by racodond** [comment]
Hi @Bertk,

Thanks for your feedback!
Pystrings cannot be ignored because they can contain placeholders.

I'll try to remove those false positives by checking if they are preceded by the include keyword.

Tell me what you think.

Thank you

Have a good day!

David

**Comment by Bertk** [comment]
Hi David,

I am not sure whether adding a check for **#include** pre-processor directive is necessary. 
This feature file is used for the C++ Community plugin tests and nobody else will do this. 

Using escape sequences "\<", "\>" might be a workaround. If this is successful a hint in the issues to use escape sequence would be nice.

I will check this with a pull request tomorrow.

Best regards
Bert
 
https://github.com/cucumber/cucumber/blob/master/gherkin/docs/ast.pdf

**Comment by Bertk** [comment]
Hi David,

I checked with this PR https://github.com/SonarOpenCommunity/sonar-cxx/pull/1609 and the escape sequence did not break the test.

I am still not sure whether a Pystring can be used to define a symbolic name for values.

Regards
Bert
