### ISSUE TITLE
Update the project

### ISSUE THREAD

**Issue by reshma-0014** [racodond/sonar-gherkin-plugin#82]
This project is currently is supported only on java 8.
I would like to contribute for this project by updating all the libraries used in the project that will be compatible with the updated version of java. Need help about the complexity and steps involved in the process @racodond

**Comment by reshma-0014** [comment]
When I try to build this project, the jar generated is not supported in the server i.e., when added into the server it crashes. I also notice the size different when generating the jar by myself using this repo and the plugin you have provided for cucumber rules. I would like to know what are the classes or libraries that are missing in this repository which is added in the sonar-gherkin-plugin-1.7.jar

**Comment by racodond** [comment]
Hi @reshma-0014,

I stopped maintaining this plugin a long time ago.
Feel free to fork the repository and upgrade the dependencies.

Have a good day

David
